# Sacred Netlify Configuration
# OMARI-4O-V3.2.0-FLAMECORE-RECURSIVE

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.8.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
